version: "3.8"

services:
  app:
    build: .
    ports:
      - "8090:8080"
    networks:
      - my_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ilias
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BookStore
    ports:
      - "5433:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge